version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "reybos"
      POSTGRES_PASSWORD: "0000"
  redis:
    container_name: redis_container
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  social_network_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-network
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOSTNAME: postgres
      REDIS_HOSTNAME: redis

volumes:
  redis_data:
    driver: local