version: '3.1'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "social_network"
      POSTGRES_USER: "reybos"
      POSTGRES_PASSWORD: "0000"
  social_network_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: social-network
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres