version: '3.9'

networks:
  chat_network:
    driver: bridge

services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_container
    ports:
      - "8000:8000"
    depends_on:
      - master
    environment:
      POSTGRES_HOSTNAME: "${COMPOSE_PROJECT_NAME:-citus}_master"
    networks:
      - chat_network

  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus"
    ports:
      - "5432:5432"
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-reybos}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-0000}"
      PGUSER: "${POSTGRES_USER:-reybos}"
      PGPASSWORD: "${POSTGRES_PASSWORD:-0000}"
      POSTGRES_DB: "dialog"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      - chat_network

  worker:
    image: "citusdata/citus"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on:
      - manager
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
    networks:
      - chat_network

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on:
      - master
    environment: *AUTH
    networks:
      - chat_network

volumes:
  healthcheck-volume: